sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            payment:
                items:
                    - admin.invoice

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
